### PR TITLE
correct lib name error, comment out failing test

### PR DESCRIPTION
**Pull request by tbrowder**
David, this now passes for me.

### CODE REVIEW

**Comment by dwarring** [comment]
I was relying on some magic in handling `libraries/` resources Rakudo. A base library name gets expanded to a platform dependent name. So on Linux the resource `libraries/ft6` resolves to `libft6.so` from `resources/libraries` in the source directory and on MacOS it expands on `libft6.dylib`.

From memory, I think I adopted this after ready this advent post from ugexe, which explains this library expansion https://perl6advent.wordpress.com/2016/12/16/day-16-the-meta-spec-distribution-and-compunitrepository-explained-ish/

Although I haven't found a clear explanation of this use of `libraries/` resources in the [Rakudo NativeCall documentation](https://docs.raku.org/language/nativecall).

**Comment by tbrowder** [comment]
I discussed this with @ugexe and he also pointed out the misspelling. On my main Debian host, in my repo from which the PR was generated, I just installed it cleanly by running:

    zef install --force-install .

The test I commented out looks incorrect for one thing because you are comparing .s (size, an integer), with .IO which I believe is a Bool.

**Comment by dwarring** [comment]
As another example,  [META6 for `Digest::Sha1::Native`](https://github.com/bduggan/raku-digest-sha1-native/blob/master/META6.json) just has `libraries/sha1` in its META6 resources.

**Comment by dwarring** [comment]
Original test was `ok $FT-WRAPPER-LIB.IO.s, $FT-WRAPPER-LIB.IO.path ~ ' library has been built';`
which intends to test for non-zero size of the library. ` $FT-WRAPPER-LIB.IO.path` is being appended to the test description.

It could maybe be written clearer, but I can't see that it's incorrect.

**Comment by tbrowder** [comment]
Okay, David, I'll check again. But I think that magic is a little suspect. 

Regarding my mstake on the "incorrect" test, isn't it redundant considering the next test?

Thanks for looking, though.

**Comment by dwarring** [comment]
Yes test can be removed. Alll the tests in `t/00sanity.t` have been recently introduced, so could all be suspect. Is it the only test file with failing tests? If it is, I'm OK in general with commenting failing tests out, or removing it entirely for now.

Note that macos github tests are failing because hardcoding the suffix to `.so.` doesn't work for them when they expect `.dylib`.

I reiterate that the module `Digest::SHA1::Native` is an example module that's relying on the same "magic" with library resources.

**Comment by tbrowder** [comment]
Sorry for the noise and trouble, David. It must have been a positron hit on a bit in my new host!

    zef install Font::FreeType

has worked three times out four now on the new host. It's currently installed and I'm not fooling with it until any update you may make.

**Comment by tbrowder** [comment]
On Sat, Aug 19, 2023 at 15:34 David Warring ***@***.***>
wrote:

> Yes test can be removed. Alll the tests in t/00sanity.t have been
> recently introduced, so could all be suspect. Is it the only test file with
> failing tests? If it is, I'm OK in general with commenting failing tests
> out, or removing it entirely for now.
>
David, see my replies in the PR. I'm sorry to have waved a false red flag
for the module.

Best regards,

-Tom

**Pull request closed without merging**
